MyTravels/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyTravels.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить меня?")]
        public bool RememberMe { get; set; }
    }
}

MyTravels/Models/ViewComponents/SidebarViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyTravels.Domain;

namespace MyTravels.Models.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public SidebarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult) View("Default", dataManager.HistoryTravel.GetHistoryTravels()));
        }
    }
}

MyTravels/Areas/Admin/Controllers/HistoryTravelController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyTravels.Domain;
using MyTravels.Domain.Entities;
using MyTravels.Service;

namespace MyTravels.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HistoryTravelController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public HistoryTravelController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new HistoryTravel() : dataManager.HistoryTravel.GetHistoryTravelById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(HistoryTravel model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                                        
                }
                dataManager.HistoryTravel.SaveHistoryTravel(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.HistoryTravel.DeleteHistoryTravel(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

MyTravels/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyTravels.Domain;

namespace MyTravels.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.HistoryTravel.GetHistoryTravels());
        }
    }
}

MyTravels/Areas/Admin/Controllers/TextFoMiController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MyTravels.Domain;
using MyTravels.Domain.Entities;
using MyTravels.Service;

namespace MyTravels.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFoMiController : Controller
    {
        private readonly DataManager dataManager;
        public TextFoMiController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFoMi.GetTextFoMiByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextFoMi model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFoMi.SaveTextFoMi(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

MyTravels/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyTravels.Models;

namespace MyTravels.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public AccountController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr)
        {
            userManager = userMgr;
            signInManager = signinMgr;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager
                        .PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MyTravels/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyTravels.Domain;

namespace MyTravels.Controllers
{

    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFoMi.GetTextFoMiByCodeWord("PageIndex"));
        }
        public IActionResult UseInfo()
        {
            return View(dataManager.TextFoMi.GetTextFoMiByCodeWord("PageUsefulinfo"));
        }
        public IActionResult Contacts()
        {
            return View(dataManager.TextFoMi.GetTextFoMiByCodeWord("PageContacts"));
        }
    }
}

MyTravels/Controllers/TravelsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MyTravels.Domain;

namespace MyCompany.Controllers
{
    public class TravelsController : Controller
    {
        private readonly DataManager dataManager;

        public TravelsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.HistoryTravel.GetHistoryTravelById(id));
            }

            ViewBag.TextFoMi = dataManager.TextFoMi.GetTextFoMiByCodeWord("PageTravels");
            return View(dataManager.HistoryTravel.GetHistoryTravels());
        }
    }
}

MyTravels/Areas/Admin/Views/HistoryTravel/Edit.cshtml
@model HistoryTravel
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}
<script src="~/js/ckeditor/ckeditor.js"></script>
<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="HistoryTravel" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>
<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyTravels/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<HistoryTravel>
@{ 
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}
<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Мои путешествия</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="HistoryTravel" asp-action="Edit" asp-route-id="">Добавить запись</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (HistoryTravel entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="HistoryTravel" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="HistoryTravel" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Travels" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }

    </div>

    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFoMi" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFoMi" asp-action="Edit" asp-route-codeWord="PageTravels">Мои Путешествия</a>
        <a asp-area="Admin" asp-controller="TextFoMi" asp-action="Edit" asp-route-codeWord="PageUsefulinfo">Полезная информация</a>
        <a asp-area="Admin" asp-controller="TextFoMi" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

MyTravels/Areas/Admin/Views/TextFoMi/Edit.cshtml
@model TextFoMi
@{ 
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}
<script src="~/js/ckeditor/ckeditor.js"></script>
<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFoMi" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>
<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyTravels/Views/Home/Contacts.cshtml
@model TextFoMi
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}
<div>
    
    @Html.Raw(Model.Text)
</div>

MyTravels/Views/Home/Index.cshtml
@model TextFoMi
@{ 
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}
<div>
    @Html.Raw(Model.Text)
</div>

MyTravels/Views/Home/UseInfo.cshtml
@model TextFoMi
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}
<div>
    @Html.Raw(Model.Text)
</div>

MyTravels/Views/Services/Index.cshtml
@model IQueryable<HistoryTravel>
@{
    TextFoMi textField = ViewBag.TextFoMi;

    ViewBag.Title = textField.MetaTitle;
    ViewBag.Description = textField.MetaDescription;
    ViewBag.Keywords = textField.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (HistoryTravel entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Travels" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

MyTravels/Views/Services/Show.cshtml
@model HistoryTravel
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>
        @Model.Title
    </h2>
    <h2>
        @Model.Subtitle
    </h2>
    <div>
        <img class="img-block" src="~/images/@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>

MyTravels/Views/Shared/Components/Sidebar/Default.cshtml
@model IQueryable<HistoryTravel>

@if (Model?.Any() == true)
{
    <section>
        <h2>Мои Путешествия</h2>
        <ul class="small-image-list">
            @foreach (HistoryTravel entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Travels" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>
                        @entity.Title
                    </h4>
                    <p>
                        @entity.Subtitle
                    </p>
                </li>
            }
        </ul>
    </section>
}

MyTravels/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>

MyTravels/Views/Shared/FooterPartial.cshtml
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-8 col-12">

                <div id="copyright">
                    &copy; @Config.MyName. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
                </div>

            </div>
        </div>
    </div>
</div>

MyTravels/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">@Config.BlogName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        <a asp-area="" asp-controller="Home" asp-action="UseInfo">Полезная информация</a>
                        <a asp-area="" asp-controller="Travels" asp-action="Index" asp-route-id="">Мои Путешествия</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                    </nav>
                </header>

            </div>
        </div>
    </div>
</div>

MyTravels/Views/Shared/MetatagsPartial.cshtml
@using MyTravels.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.BlogName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />

}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

MyTravels/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

MyTravels/Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

MyTravels/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")   
</head>
<body>
    <div id="page-wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <!-- Main -->
        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium">
                        @RenderBody()
                    </div>
                    @await Html.PartialAsync("SidebarPartial")
                </div>                    
            </div>
        </div>

        @await Html.PartialAsync("FooterPartial")
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>

MyTravels/Views/Travels/Index.cshtml
@model IQueryable<HistoryTravel>
@{
    TextFoMi textFoMi = ViewBag.TextFoMi;

    ViewBag.Title = textFoMi.MetaTitle;
    ViewBag.Description = textFoMi.MetaDescription;
    ViewBag.Keywords = textFoMi.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (HistoryTravel entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Travels" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

MyTravels/Views/Travels/Show.cshtml
@model HistoryTravel
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>
        @Model.Title
    </h2>
    <h2>
        @Model.Subtitle
    </h2>
    <div>
        <img class="img-block" src="~/images/@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>